### ISSUE TITLE
Simplify URLs of pages including security page, terms of use, contact us (consistency with privacy)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1008]
**Story**
When following routes in Notify I don't want to have URLs that have an extra directory on them so that users can try and find pages we have removed. 

**What?**
We changed pages and the route map needs updated.

**Why?**
We don't use the same structure for our pages as GDS, but we still have the old URLs from GDS

**Done When?**
Contact, Terms of use, and Security, are all one directory deep and we don't have any broken links. 

**Notes**
Fix long URLs

Pages not housed in features have URLs that look like they are...consider matching the URL structure of the Privacy page (ie. https://notification.alpha.canada.ca/privacy)

# Security

Currently:
https://notification.alpha.canada.ca/features/security

Consider instead:

https://notification.alpha.canada.ca/security

# Terms of use

Currently:
https://notification.alpha.canada.ca/features/terms 

Consider instead:
https://notification.alpha.canada.ca/terms

# Contact us

Currently:
https://notification.alpha.canada.ca/support/ask-question-give-feedback

Consider instead:
https://notification.alpha.canada.ca/contact

___

-- see if there are other URLs we can simplify this way.

**Comment by AntoineAugusti** [comment]
@bryan-robitaille There are more pages under the `/features` namespace.

Currently in use:

- https://notification.alpha.canada.ca/features/terms
- https://notification.alpha.canada.ca/features/messages-status 
- https://notification.alpha.canada.ca/features/security
- https://notification.alpha.canada.ca/features/email
- https://notification.alpha.canada.ca/features/sms
- https://notification.alpha.canada.ca/features/templates

And the complete list defined in the app

- /features/email
- /features/letters
- /features/messages-status
- /features/roadmap
- /features/security
- /features/sms
- /features/templates
- /features/terms
- /features/using-notify

Is the goal to drop the `/features` part? Is it acceptable to have this namespace since we have quite a few pages?

**Comment by anikbrazeau** [comment]
CC @ioanacontu 

I think it's fine to drop features from all of them since none of them relate in the architecture / navigation we're proposing. 

In future, we anticipate only the features page to live under /features (https://notification.alpha.canada.ca/features)

These pages are/will be gone:
/email
/sms
/letters
/using-notify

These pages will likely be stand-alone in the footer:
/roadmap
/security
/terms

These pages may eventually be rolled into guidance for how to use Notify:
guidance/templates
guidance/messages-status

**Comment by brdunfield** [comment]
@anikbrazeau Just want to get some clarification on this - the pages you flagged (such as /using-notify) - are they ok to delete at this time?

**Comment by anikbrazeau** [comment]
I think we can go either way (keep for now or delete), we currently don't display `/letters` and `/using-notify`, so we could remove them fully to clean things up? 

As for `/email` and `/sms`, the upcoming changes we've got in progress to the [features page](https://www.figma.com/file/bgHBy4o1STV4DlpkpdtIUV/Unauthenticated-pages?node-id=6%3A2093) will make these two pages unnecessary/obsolete, and therefore we could delete them at that moment in time?
