### ISSUE TITLE
Make account changes email more bilingual

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-api#1016]
**steps to reproduce**
1) Navigate to your profile in French
2) Select to changez votre Nom
3) Lissez votre corriel. 

**Expected Behaviour**
- Email says Name changed, Nom Changed.

**Actual** 
See Screen shot, says name twice

**Notes**
Users get an email when details of their account change (directly from api). These emails have bilingual content, but the actual items that are changing are only in English:

![image](https://user-images.githubusercontent.com/8228248/86806522-f2aeb100-c046-11ea-83cd-33497d335239.png)

We should make the list bilingual as well. This would probably entail:
* making the template for that email take two `change_type` variables instead of one
* making a translations dict for the words that appear (name, password, ...)
* using the translations dict to set the `change_type` variables.

Note that currently the staging template is different from the production template.

**Comment by anikbrazeau** [comment]
Translate ((change_type)) 

<img width="562" alt="Screen Shot 2020-07-09 at 7 35 24 AM" src="https://user-images.githubusercontent.com/38330843/87035245-0da03300-c1b7-11ea-8b2a-aba74f3604d3.png">

Are there other possible variables that are untranslated too?

**Comment by anikbrazeau** [comment]
In "Automated You're Live Now" --> ((message limit)) variable format would be different in English and French
ex: EN = 25,000 // FR = 25 000

**Comment by anikbrazeau** [comment]
In a similar vein, should we be linking directly to the FR URL in the FR part of the email? For example --> communiquez avec nous goes to FR Contact us page?

**Comment by brdunfield** [comment]
I don't think we currently have separate URLs for languages. If the user's browser language is set to French, they will see the french page on load.

**Comment by willeybryan** [comment]
On getting rid of ((change_type)) and it's impact on the user journey 

The history for this feature is that we added that to be compliant with Government of Canada security policies.
It also is generated when some one else, like an administrator edits a users information. Including a users system access or permissions.
The only time anyone has ever emailed us, I had changed their permissions in a service at the request of the service owner, and they emailed us.

It was helpful to know that their permissions had changed so I could be certain it was my actions that caused it.

According to the security control, we need to alert them that there has been a change, but not explicitly to what it was.

So we can remove the name, but for the two edge cases, I would want to communicate what happened. The edge cases being  an admin changes some one's permissions or an admin changes a users two factor authentication.

This is because this is a scary email to receive, it is less scary if my boss emailed me earlier saying he was going to change my two factor authentication, and I think not scaring people is important to the user journey.
