### ISSUE TITLE
Investigate and document Pod Crashes (Time boxed 1 day)

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#1064]
**Investigate**
- Why are the pods Crashing?
- What scenarios do they crash?
- What happens to pod CPU, RAM, Network, and Disk usage in a crash?
- How many episodes are we talking about and when do they happen ?

**Document?**
- Findings from the above for review of a future developer

**Done When**
- Document created for sharing

**Comment by sastels** [comment]
Draft document
https://docs.google.com/document/d/1Dt1vAsDXlDs3F2c6nMyTJS76U31fHlnHNl5q0FYdtEQ

**Comment by sastels** [comment]
@brdunfield @willeybryan @ClementineHahn could you take a look at [the document](https://docs.google.com/document/d/1Dt1vAsDXlDs3F2c6nMyTJS76U31fHlnHNl5q0FYdtEQ) and provide any thoughts? Thanks!

**Comment by ClementineHahn** [comment]
how to follow up on this  with **Recommendations** (extracted from doc linked)

- [ ] Get performance monitoring running on prod > Should become a new card @willeybryan @sastels @brdunfield @maxneuvians 
- [ ] Create an alarm to alert on multiple api crashes
- [ ] Monitor for crashes on staging (or prod with perf monitoring). Next time it happens, see if there are any perf monitoring abnormalities.
- [ ] Determine if there is more we should be logging
- [ ] Get api running with gunicorn locally (rather than flask) and try to reproduce errors
