### ISSUE TITLE
Whitespace disappears before vertical bar in email subject headings

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/notification-api#1139]
Hello! 

We are trying to send a subject line like `Change your password | COVID Alert Portal`, but the template strips the whitespace before the vertical bar.

While editing, it looks right:

![image](https://user-images.githubusercontent.com/2454380/93490894-0db76000-f8d7-11ea-9490-1b791f5ac216.png)

But then on the "view template" screen, you can see the space is missing for the subject heading. (Not the sender though.)

![image](https://user-images.githubusercontent.com/2454380/93490983-2758a780-f8d7-11ea-8f10-89193a40c622.png)

Interestingly, it's also affecting your account modification email subject headings.

![image](https://user-images.githubusercontent.com/2454380/93491149-5a02a000-f8d7-11ea-833d-48de815b9fba.png)

Again, pretty minor bug but I figured I should mention it.

**Comment by AntoineAugusti** [comment]
Investigated a bit this issue and it's caused by the fact that there are a few rules to clean what's written in subject/body. Enforcing a space after a comma/dot, removing a space before a pipe (this bug) and many others.

The regex causing the pipe problem is here https://github.com/cds-snc/notification-utils/blob/39eb59a9b6befc5f6ad50d74f03ed277c858c9be/notifications_utils/formatters.py#L65. The subject field is cleaned this way https://github.com/cds-snc/notification-utils/blob/39eb59a9b6befc5f6ad50d74f03ed277c858c9be/notifications_utils/template.py#L275-L285. The rule we are interested in is `remove_whitespace_before_punctuation`.

I'd be in favour of removing the pipe from the list. It seems acceptable to have whitespace before a pipe.

@bryan-robitaille if you want to review other rules, they are located in this file https://github.com/cds-snc/notification-utils/blob/master/notifications_utils/template.py and method names read nicely
