### ISSUE TITLE
Missing personalization throws breaking exception

### ISSUE THREAD

**Issue by jidicula** [cds-snc/notification-api#1236]
When calling `send_email_notification()` on a `NotificationsAPIClient` instance with a template containing personalizations, the method will throw an exception if any of the personalizations are missing:

```
API POST request on https://api.notification.alpha.canada.ca/v2/notifications/email failed with 400 '[{'error': 'BadRequestError', 'message': 'Missing personalisation: environment'}]'
```

This is more of a design-related question, but is it the correct behaviour for the client to throw an Exception in this case, or should it instead be raising a Warning to stdout?

---

[We](https://github.com/Digital-HR) ran into this issue when we updated a template with new personalizations for our staging environments, but our production environment had Notify calls pointing to the same template and immediately started failing loudly. Do you recommend using separate templates for each environment they may be used in?

**Comment by AntoineAugusti** [comment]
Hi @jidicula,

The behaviour you described in your question is currently a feature but I agree it may be misleading, let me explain how it works at the moment. When you create templates on Notify and then send notifications using the template UUID, the latest version of the template will be used. This is convenient if you have a "stable" template and you want to tweak some wording, without changing variables. This becomes an issue, as you experienced, if you use the same template in various environments and you add/delete/update variables. The API responds with a 400 if you're missing personalisation data, that's expected: all personalisation keys are required.

> Do you recommend using separate templates for each environment they may be used in?

I think that it may be a safer bet for you. At the moment the API does not let you pin down the version when specifying a template (you would need to pass the template UUID + the template version). To avoid breaking your production code when you're looking at changing your templates, it may be easier to differentiate templates between staging and production. You could use folders for that. You would have different template UUIDs between staging and production, you could change these values using environment variables.

I'm sorry you experienced this behaviour the hard way and that your production environment failed because of that. We plan to work more on templates in the coming months and we'll make sure this is properly documented in the technical documentation and in the UI if you add/delete/update personalisation keys.

I'll pass on your feedback to our Product team for consideration.

**Comment by jidicula** [comment]
Thanks @AntoineAugusti! No need to apologize - this was a mistake on our end in how we were using the product. We'll set up different templates for each environment to prevent running into this pitfall again.

I'll leave it to you to decide if you want to close this issue, but from my end I have the information I need. Thanks again!

**Comment by AntoineAugusti** [comment]
The Notify app warns you when you add/update/delete variables on the UI but it's easy to miss. We'll improve that in the future.

![image](https://user-images.githubusercontent.com/295709/110172928-de84a480-7dcb-11eb-9af5-7ad6d0b1f82a.png)
