### ISSUE TITLE
We need a product blurb for the website

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#138]
**What?**
- See https://digital.canada.ca/products/
- Notification needs an Alpha product blurb
- No partner, Instead say service and link to notification.cdssandbox.xyz
- Contact is will be my @tbs-sct.gc.ca email
- Once written have It translated

**Why?**
- Raise awareness
- Something to direct users to it

**Comment by willeybryan** [comment]
Started here https://docs.google.com/document/d/1BJoj2bpB6aDxu5UmmBgNBxzCOPNlYlqsf4eIbBLYlwc/edit?disco=AAAADSPaSu4&ts=5d41921c

**Comment by YedidaZalik** [comment]
Exploring an easy and efficient system that helps Canada send notifications to people who use government services.

**Comment by YedidaZalik** [comment]
@willeybryan please review:
*Send email and text message updates about government services* Alpha

Blurb paragraph: Exploring an easy and efficient system that helps Canada send notifications to people who use government services. 

Service (instead of partner): notification.cdssandbox.xyz

Contact: Bryan Willey  ( Email hyperlink as per website style to bryan.willey@tbs-sct.gc.ca)

**Comment by willeybryan** [comment]
looks good to me
