### ISSUE TITLE
Broken Links Checking - To improve coverage and user experience - Reduce number of support calls

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#148]
**What?**
- Using something like 404sentry or another system that can find broken links (Devs Choice based on our needs) we want to scan Notification for broken links
- Optimally this would be a routine check so we can find potential broken links before users (Weekly?) (Daily?) (Continuously?)

**Why?**
- If a user finds a broken link they are going to have a bad time
- Users may log issues for broken links creating overhead

**Comment by maxneuvians** [comment]
Couple of actions taken around this:

- Created a custom Google Analytics report for "Page not found". This can be found in Google Analytics saved reports.

- Added two automatic metrics to Stackdriver logging that show how many 404 are encountered. If those metrics are high, we know there is a problem.

- Also added Sentry(https://github.com/cds-snc/notification-api/pull/197) to both the API and Admin(https://github.com/cds-snc/notification-admin/pull/113).

The issue is that any tool will only be able to scan public URLs. The bulk of the app is behind the login. Currently we only have 10 public URLs that will probably stay static. Any changes to them will be tested using the Review app. If we do go down this road - we should build a generic github action using https://github.com/linkchecker/linkchecker much like we did with the a11y scanning.

**Comment by willeybryan** [comment]
How can I access our Google Analytics for this tool?

**Comment by willeybryan** [comment]
I am also not getting any stack driver information past July 29th it seems:
https://app.google.stackdriver.com/dashboards/3445856516295532855?project=notification-canada-ca&timeDomain=6w
