### ISSUE TITLE
Implement and review GDS AWS Alarms

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#377]
**What?**
- Implement GDS Terraform File alarms
- Connect the alarms to email the team? Slack the team? 
- Evaluate the alarms and cut ones you don't think add value/would annoy us/false results as I imagine the alarms won't connect seamlessly with out changes. 

**Why?**
- For live usage these alarms can help us identify things we need to fix or services we need to audit because they are spamming

**Comment by willeybryan** [comment]
I can't upload the terraform file to github without zipping it. Max and Tim have a copy in their email.

**Comment by maxneuvians** [comment]
These are all for ELB alarms. Implemented:

`UnHealthyHostCount`
`HealthyHostCount`
`Latency`
`SurgeQueueLength`

Could not implement:

`SpilloverCount `
`BackendConnectionErrors`

because we have no data and 

`HTTPCode_Backend_5XX`

because TLS termination in the cluster stops the EBS from reading them ?!?
