### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#675]
**Story**
When I can't connect to Notify I want to go to a different site to check to see if it is up or if it is just me,.

**What?**
- on separate domain Status page host a status page ( notify.status.cds-snc.ca ?) 
- Suggestion was to use this page https://status.notifications.service.gov.uk/ 
- We don't really need to worry too much about styling right now

**Why?**
- Moves us closer to enterprise level service for live and beta

**notes**
- Consider making a general status page for all platform elements or coordinating with Stephane
- We don't need the issues calender just something like this
![image](https://user-images.githubusercontent.com/46505127/76446766-e7e85600-639d-11ea-8d43-2a5d5cc5bbcb.png)

**Comment by timarney** [comment]
> We don't really need to worry too much about styling right now
- https://notification.alpha.canada.ca/_status 

;)

**Comment by sboisvert** [comment]
https://github.com/cds-snc/we_are_platform/issues/46

**Comment by sboisvert** [comment]
Status page now works in both languages. It does need to be checked over. @anikbrazeau pourrait tu regarder au traductions que j'ai fait (okay, que DeepL a fait)
[fr.yaml.txt](https://github.com/cds-snc/notification-api/files/4351295/fr.yaml.txt)
Et confirmer ce que on devrais changer?

https://cds-snc.statuspal.io/?lang=fr

Created https://github.com/cds-snc/dns/pull/99
So that we can create status-statut.cds-snc.ca
