### ISSUE TITLE
Missing FR string for "Sent messages" title and navigation in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#776]
Ensure French shows French title and menu item for "Sent messages"

Should say **"Messages envoyés"**

<img width="729" alt="Screen Shot 2020-04-16 at 2 53 11 PM" src="https://user-images.githubusercontent.com/38330843/79777176-de3f0000-8304-11ea-8618-b224dad42ec9.png">

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by smcmurtry** [comment]
Okay this is only visible if your account does not have permission to view the dashboard for the service. Also there is a styling issue with the search bar because the fr string is longer:
<img width="1039" alt="Screen Shot 2020-04-30 at 3 45 49 PM" src="https://user-images.githubusercontent.com/5498428/80762480-dd268380-8af9-11ea-9cf0-94fc9ad42758.png">
