### ISSUE TITLE
FR example/instruction for CSV upload

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#881]
Currently:
"Enregistrez votre fichier en format CSV, TSV, ODS, or Microsoft Excel spreadsheet"

Replace with this:
"Enregistrez votre fichier comme tableur, en format CSV, Excel, TSV ou ODS"

<img width="498" alt="Screen Shot 2020-05-21 at 9 57 14 AM" src="https://user-images.githubusercontent.com/38330843/82594912-cb715280-9b72-11ea-9bd0-191592c5e4c5.png">

**Comment by smcmurtry** [comment]
As discussed IRL with @anikbrazeau, we will use "Enregistrez votre fichier comme tableur, en format CSV, TSV, ODS ou Excel" so that we don't have to change the order of the acronyms for english and french, since they are all in special acronym tags:
![Screen Shot 2020-06-02 at 2 00 32 PM](https://user-images.githubusercontent.com/5498428/83564127-70781d80-a4d9-11ea-9f1f-154edf357526.png)
