### ISSUE TITLE
Enforce local-part email length to avoid getting quarantined by rfc-compliant systems.

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#918]
Emails from our going into a blackhole on the way to ESDC's staff. The user is triaging from his end, he's mentioned it didn't hit his junkbox, so likely at the exchange level.
@obrien-j asked Calvin Rodo to verify this if possible with his esdc account to confirm. If so, we'll need to action something within SSC as they run their exchange server.

John O'Brien  : in theory, we likely also want to have this conversation more broadly with SSC email services to make sure this isn't a repeat occurence.

**Comment by ClementineHahn** [comment]
Things to get clarity on before adding to backlog:
- clarify if there is any part of the solution on Notify side 
- if follow up from ESDC and SSC indicate accountability on the follow up and the contacts 
- indicates a clear done when and what resolutions looks like 

Thanks !

**Comment by obrien-j** [comment]
After a bit of digging and random troubleshooting, seem to have confirmed initial suspicions that this is related to an inline mail filter that actually respects the local-part length limitation as described in the following RFC. https://tools.ietf.org/html/rfc5321#section-4.5.3.1.1

Recommended action items:
[ ] Review all existing services for non-compliant service names and work with the owners to create something under the RFC limit.
[ ] Implement a check at the 'create service' level, that prevents new services from creating non-compliant service names.
[ ] Create helpful guidance on how to shorten that super long name you really think you need but seriously no one other than you thinks is cool.
[ ] Raise a support ticket with AWS to get an idea if this is expected behaviour on their part, and how we might be able to leverage a more 'strict' rfc compliance mode if possible to avoid similar problems in the future.
[ ] <new ticket/card> Initiate a dialogue with SSC Email Services Directorate to ensure that any emails from our service that get flagged are instantly triaged to our attention.

**Comment by obrien-j** [comment]
I just sent out a Question to Joel, our AWS SA on the SES/strict compliance mode item above., cc'd @sastels

**Comment by willeybryan** [comment]
They replied:
In addition to the previously whitelisted “notification.alpha.canada.ca” and “sc.m.notification.alpha.canada.ca,” we’ve added “@amazonses.com” 

That will probably do it for them, but we need to make sure that in the future we pass an email safe list with all those domains on it/our future non-alpha ones.
