### ISSUE TITLE
When error message appears -- does not focus on error message [L]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#941]
**Done When**
- Production mouse focuses on an error message when generated

Does not focus on error message after there was an error. You want focus to go there.

This is happening on the Log in page but could be happening on other pages also. Probably happening elsewhere.

https://docs.google.com/document/d/1JaJzEnQ7M6tQRziwEC1q8_UUQBizAdVRtUashXdYZeo/edit

**Comment by brdunfield** [comment]
The behaviour I am seeing with VoiceOver on the login page is that when I submit the form with errors, the focus jumps up to the first field with errors, and VoiceOver reads the field label and error. If the entire form errors (instead of a specific field), the focus jumps up to the overall error and VoiceOver reads it.

I'm not 100% clear on what needs changing.

**Comment by brdunfield** [comment]
A possible improvement I can suggest is adding "aria-invalid" to error fields, which in VoiceOver adds "Invalid Data" to the already present reading of the field data, label, and error message.

I've chatted with Anik and Ioana and we collectively can't figure out whether this requires any work. I am going to park this for now and suggest I / we speak with Julianna again to re-validate what / if this requires any work
