### ISSUE TITLE
Back up tidy up for privacy

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#974]
**Story**
When our daily backup system runs it creates a snap snot of the database. These database back ups should not be stored more than 30 days as that is the longest a user can select to retain their data is 30 days. So that should the backups become compromised, we are at no greater privacy risk then the system being compromised.

**What?**
- Find out where we store out backups (Probably from Max, probably some s3 bucket.)
- Set up an auto clean up script or AWS operation to run every 24 hours and blow up anything older than 30 days
- Run the operation/script and clean up the back logs
- Check back the next day to make sure it did it for the 1 new backup that it should scrub.

**Why?**
- Reduction in privacy impact exposure
- Current policy has us manually deleting backups every 45 days and that isn't sustainable.

**Comment by brdunfield** [comment]
Current situation:
- Local backups every day in the same AWS account as production:
 - System backups that are automatically deleted
 - "Manual" backups that are created every day, and exported into another AWS account (so it's not all in one place). These are not automatically deleted and are capped at 100 snapshots.

- The backups in the alternate account are also considered "Manual" and are not automatically deleted, and are capped at 100 snapshots

To Note:
Once the limit of 100 snapshots has been reached, it looks like the whole process shuts down. Old ones are not automatically deleted. Therefore no new snapshots can be created and exported.

Apparently, the automatic snapshots cannot be used with the export script to the alternate location, which is why it's being done with Manual snapshots.

**Comment by brdunfield** [comment]
I have manually deleted snapshots older than 30 days for now while I work on this.

**Comment by willeybryan** [comment]
The solution for beta can be that we manually clean up the backups once a month while we build a better solution over time. 

We just need to satisfy the security control. If I write a policy saying we manually delete them, then we do it. thats good.

Just means more future work.

**Comment by ClementineHahn** [comment]
Work finished by @brdunfield witing for @willeybryan to review and close it once considered done

**Comment by ClementineHahn** [comment]
@willeybryan to review and close when ok
